#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sfd_threshold_optimizer.py — SFD Threshold Optimizer v1.0
Reads sfd_backtest_report.json and recommends optimal thresholds.

Logic:
  1. Load backtest report (generated by sfd_backtest_analyzer.py)
  2. Evaluate data sufficiency (min 20 trading days recommended)
  3. Find best threshold combination by multi-criteria scoring:
       - reserve_win_rate (weight 40%)
       - reserve_avg_return (weight 35%)
       - reserve_count >= MIN_RESERVE_COUNT (weight 25%)
  4. Compare vs current thresholds
  5. Output recommendation with confidence level

Usage:
  py tools/sfd_threshold_optimizer.py
  py tools/sfd_threshold_optimizer.py --apply   (write to threshold.json)

Version: v1.0
Author: Claude Sonnet 4.6 (2026-06-07)
"""

import argparse
import json
import sys
from datetime import date
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_PIPELINE_ROOT = _HERE.parent
_LATEST = _PIPELINE_ROOT / "outputs" / "latest"

REPORT_JSON    = _LATEST / "sfd_backtest_report.json"
THRESHOLD_JSON = _LATEST / "sfd_threshold_recommendation.json"

# Current production thresholds
CURRENT_RESERVE = 90
CURRENT_WATCH   = 70

# Minimum data requirements
MIN_TRADING_DAYS  = 20   # < 20일: LOW confidence
GOOD_TRADING_DAYS = 60   # >= 60일: HIGH confidence
MIN_RESERVE_COUNT = 5    # reserve 건수 최소치 (너무 적으면 통계 무의미)

# Scoring weights
W_WIN_RATE   = 0.40
W_AVG_RETURN = 0.35
W_COUNT      = 0.25


def load_report() -> dict:
    if not REPORT_JSON.exists():
        print(f"[OPTIMIZER] Report not found: {REPORT_JSON}")
        print("  -> Run sfd_backtest_analyzer.py first")
        sys.exit(1)
    with open(REPORT_JSON, encoding="utf-8") as f:
        return json.load(f)


def get_confidence(total_dates: int) -> str:
    if total_dates < MIN_TRADING_DAYS:
        return "LOW"
    elif total_dates < GOOD_TRADING_DAYS:
        return "MEDIUM"
    else:
        return "HIGH"


def score_threshold(entry: dict, all_entries: list) -> float:
    """
    Multi-criteria score for a threshold combination.
    Normalizes each metric across all combinations.
    """
    wr  = entry.get("reserve_win_rate") or 0
    ar  = entry.get("reserve_avg_return") or -99
    cnt = entry.get("reserve_count") or 0

    # Normalize win_rate (0-100 -> 0-1)
    max_wr = max((e.get("reserve_win_rate") or 0) for e in all_entries) or 1
    norm_wr = wr / max_wr

    # Normalize avg_return (shift to positive range)
    returns = [(e.get("reserve_avg_return") or -99) for e in all_entries]
    min_ar, max_ar = min(returns), max(returns)
    rng = max_ar - min_ar if max_ar != min_ar else 1
    norm_ar = (ar - min_ar) / rng

    # Count bonus: penalize if below MIN_RESERVE_COUNT
    count_score = min(cnt / MIN_RESERVE_COUNT, 1.0)

    return round(W_WIN_RATE * norm_wr + W_AVG_RETURN * norm_ar + W_COUNT * count_score, 4)


def analyze(report: dict) -> dict:
    meta       = report.get("meta", {})
    total_dates = meta.get("total_dates", 0)
    valid_count = meta.get("valid_return_count", 0)
    confidence  = get_confidence(total_dates)

    thresh_data = report.get("threshold_simulation", {})
    if not thresh_data:
        return {
            "status": "NO_DATA",
            "message": "No threshold simulation data. Run analyzer first.",
            "confidence": confidence,
        }

    all_entries = list(thresh_data.values())

    # Score all combinations
    scored = []
    for key, entry in thresh_data.items():
        s = score_threshold(entry, all_entries)
        scored.append({**entry, "composite_score": s, "key": key})

    scored.sort(key=lambda x: x["composite_score"], reverse=True)
    best = scored[0]

    # Current threshold stats
    current_key = f"R{CURRENT_RESERVE}_W{CURRENT_WATCH}"
    current = thresh_data.get(current_key, {})

    # Build recommendation
    rec = {
        "generated_at":   str(date.today()),
        "confidence":     confidence,
        "data_summary": {
            "trading_days":  total_dates,
            "valid_returns": valid_count,
            "date_range":    f"{meta.get('date_range_start')} ~ {meta.get('date_range_end')}",
        },
        "current_thresholds": {
            "reserve": CURRENT_RESERVE,
            "watch":   CURRENT_WATCH,
            "reserve_win_rate":   current.get("reserve_win_rate"),
            "reserve_avg_return": current.get("reserve_avg_return"),
            "reserve_count":      current.get("reserve_count"),
            "watch_win_rate":     current.get("watch_win_rate"),
        },
        "recommended_thresholds": {
            "reserve": best["reserve_thresh"],
            "watch":   best["watch_thresh"],
            "reserve_win_rate":   best.get("reserve_win_rate"),
            "reserve_avg_return": best.get("reserve_avg_return"),
            "reserve_count":      best.get("reserve_count"),
            "watch_win_rate":     best.get("watch_win_rate"),
            "composite_score":    best["composite_score"],
        },
        "change_needed": (
            best["reserve_thresh"] != CURRENT_RESERVE or
            best["watch_thresh"]   != CURRENT_WATCH
        ),
        "top5_candidates": [
            {
                "key":               s["key"],
                "reserve":           s["reserve_thresh"],
                "watch":             s["watch_thresh"],
                "reserve_win_rate":  s.get("reserve_win_rate"),
                "reserve_avg_ret":   s.get("reserve_avg_return"),
                "reserve_count":     s.get("reserve_count"),
                "composite_score":   s["composite_score"],
            }
            for s in scored[:5]
        ],
        "advisory": _build_advisory(confidence, total_dates, best, current),
    }
    return rec


def _build_advisory(confidence: str, days: int, best: dict, current: dict) -> str:
    lines = []
    if confidence == "LOW":
        lines.append(f"[LOW CONFIDENCE] Only {days} trading days of data.")
        lines.append(f"  Minimum {MIN_TRADING_DAYS} days required for reliable recommendation.")
        lines.append(f"  Keep current R={CURRENT_RESERVE}/W={CURRENT_WATCH} until more data accumulates.")
    elif confidence == "MEDIUM":
        lines.append(f"[MEDIUM CONFIDENCE] {days} trading days analyzed.")
        lines.append(f"  Recommendation valid but may shift with more data.")
        r_best = best.get("reserve_thresh", CURRENT_RESERVE)
        w_best = best.get("watch_thresh", CURRENT_WATCH)
        if r_best != CURRENT_RESERVE or w_best != CURRENT_WATCH:
            lines.append(f"  Suggested change: R={CURRENT_RESERVE}->{r_best} / W={CURRENT_WATCH}->{w_best}")
            lines.append(f"  Apply only after 60+ days of data for HIGH confidence.")
        else:
            lines.append(f"  Current thresholds R={CURRENT_RESERVE}/W={CURRENT_WATCH} appear optimal.")
    else:
        lines.append(f"[HIGH CONFIDENCE] {days} trading days analyzed.")
        r_best = best.get("reserve_thresh", CURRENT_RESERVE)
        w_best = best.get("watch_thresh", CURRENT_WATCH)
        if r_best != CURRENT_RESERVE or w_best != CURRENT_WATCH:
            lines.append(f"  RECOMMEND CHANGE: R={CURRENT_RESERVE}->{r_best} / W={CURRENT_WATCH}->{w_best}")
            wr_curr = current.get("reserve_win_rate", 0) or 0
            wr_best = best.get("reserve_win_rate", 0) or 0
            lines.append(f"  Win rate improvement: {wr_curr}% -> {wr_best}%")
        else:
            lines.append(f"  Current thresholds are optimal. No change needed.")
    return " | ".join(lines)


def print_recommendation(rec: dict):
    print("\n" + "=" * 60)
    print("  SFD THRESHOLD OPTIMIZER — RECOMMENDATION")
    print("=" * 60)

    ds = rec.get("data_summary", {})
    print(f"  Confidence : {rec['confidence']}")
    print(f"  Data range : {ds.get('date_range')}")
    print(f"  Days / Valid returns : {ds.get('trading_days')} / {ds.get('valid_returns')}")
    print()

    curr = rec.get("current_thresholds", {})
    print(f"[ CURRENT ]  R={curr['reserve']} / W={curr['watch']}")
    print(f"  reserve_win_rate={curr.get('reserve_win_rate')}%  "
          f"avg_return={curr.get('reserve_avg_return')}%  "
          f"count={curr.get('reserve_count')}")

    print()
    rec_t = rec.get("recommended_thresholds", {})
    marker = "✅ NO CHANGE" if not rec.get("change_needed") else "⚠️  CHANGE SUGGESTED"
    print(f"[ RECOMMENDED ]  R={rec_t['reserve']} / W={rec_t['watch']}  {marker}")
    print(f"  reserve_win_rate={rec_t.get('reserve_win_rate')}%  "
          f"avg_return={rec_t.get('reserve_avg_return')}%  "
          f"count={rec_t.get('reserve_count')}")

    print()
    print("[ TOP 5 CANDIDATES ]")
    for c in rec.get("top5_candidates", []):
        print(f"  {c['key']:12s}  wr={c['reserve_win_rate']}%  "
              f"ret={c['reserve_avg_ret']}%  "
              f"cnt={c['reserve_count']}  score={c['composite_score']}")

    print()
    print("[ ADVISORY ]")
    for line in rec.get("advisory", "").split(" | "):
        print(f"  {line}")

    print("=" * 60 + "\n")


def run(apply: bool = False):
    report = load_report()
    rec    = analyze(report)

    # Save recommendation
    _LATEST.mkdir(parents=True, exist_ok=True)
    with open(THRESHOLD_JSON, "w", encoding="utf-8") as f:
        json.dump(rec, f, ensure_ascii=False, indent=2)
    print(f"[OPTIMIZER] Recommendation saved: {THRESHOLD_JSON}")

    print_recommendation(rec)

    if apply:
        if rec.get("confidence") in ("LOW",):
            print("[OPTIMIZER] BLOCKED: confidence too low to apply changes.")
        elif rec.get("change_needed"):
            rt  = rec["recommended_thresholds"]
            out = {
                "THRESHOLD_RESERVE": rt["reserve"],
                "THRESHOLD_WATCH":   rt["watch"],
                "applied_at":        str(date.today()),
                "confidence":        rec["confidence"],
            }
            apply_path = _LATEST / "sfd_threshold_active.json"
            with open(apply_path, "w", encoding="utf-8") as f:
                json.dump(out, f, indent=2)
            print(f"[OPTIMIZER] Thresholds applied -> {apply_path}")
            print(f"  R={rt['reserve']} / W={rt['watch']}")
        else:
            print("[OPTIMIZER] No change needed. Current thresholds are optimal.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SFD Threshold Optimizer v1.0")
    parser.add_argument("--apply", action="store_true",
                        help="Write recommended thresholds to sfd_threshold_active.json")
    args = parser.parse_args()
    run(apply=args.apply)
